[user]
name = "daniel daum"
email = "daniel@danieldaum.net"

[ui]
pager = "delta"
diff.format = "git"
diff.tool = "difftastic"
default-command = "log"

[git]
write-change-id-header = true
sign-on-push = true


[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[aliases]
init  = ["git", "init"]
push  = ["git", "push"]
pull  = ["git", "fetch"]
clone = ["git", "clone"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[templates]
log = """
  if(root,
    format_root_commit(self),
    label(if(current_working_copy, "working_copy"),
      concat(
        separate(" ",
          change_id.short(),
          if(empty, label("empty", "(empty)")),
          if(description,
            description.first_line(),
            label(if(empty, "empty"), description_placeholder),
          ),
          bookmarks,
          if(conflict, label("conflict", "conflict")),
        ) ++ "\n",
      ),
    )
  )
"""

[merge-tools.difftastic]
program = "difft"
diff-args = ["--color=always", "--display=side-by-side", "$left", "$right"]